# Combined Docker Compose for DataIngestion (Rust + Python Pipelines)
# Located in DataIngestion/docker-compose.yml

services:
  # --- Rust Pipeline Services ---
  rust_pipeline:
    build:
      context: ./rust_pipeline # Adjusted build context
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    volumes:
      # Mount the data directory relative to DataIngestion parent
      - ../Data:/app/data:ro
      - ./rust_pipeline/pipeline_logs:/app/logs:rw # Adjusted path
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DATA_SOURCE_PATH: /app/data
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    networks:
      - ingestion-net

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - ingestion-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Single Database Service (from rust_pipeline definition)
  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      # Mount main init script first (for sensor_data table)
      - ./rust_pipeline/db_init/init.sql:/docker-entrypoint-initdb.d/00_init_sensor_data.sql:ro # Adjusted path
      # Mount script to create extra DBs needed by Python pipeline services
      - ./simulation_data_prep/create_extra_dbs.sql:/docker-entrypoint-initdb.d/01_create_extra_dbs.sql:ro # Adjusted path
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ingestion-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_SETUP_EMAIL: "admin@example.com"
      PGADMIN_SETUP_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./rust_pipeline/servers.json:/pgadmin4/servers.json:ro # Adjusted path
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ingestion-net

  # --- Python Pipeline Services ---
  data-prep:
    build:
      context: ./simulation_data_prep # Adjusted build context
      dockerfile: Dockerfile
    env_file:
      - ./.env # Load from the same directory as this docker-compose.yml
    command: >
      sh -c '
        echo "Waiting for Orion server to be ready...";
        until curl -fs http://orion:4200/health/ready; do
          echo "waiting for Orion...";
          sleep 2;
        done;
        echo "Orion ready. Starting Prefect worker...";
        prefect worker start --pool default-process-pool -q default;
      '
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    depends_on:
      db:
        condition: service_healthy
      orion:
        condition: service_healthy
      mlflow-server:
        condition: service_started
    volumes:
      - ./simulation_data_prep/src:/app/src
      - ./simulation_data_prep/output:/app/output
      - ./simulation_data_prep/plant_config.json:/app/plant_config.json
      - ./simulation_data_prep/feast_repo:/app/feast_repo
      - ./simulation_data_prep/great_expectations:/app/great_expectations
      - ./simulation_data_prep/dao:/app/dao
      - ./simulation_data_prep/transforms:/app/transforms
      - ./simulation_data_prep/loading:/app/loading
      - ./simulation_data_prep/validation:/app/validation
      - prefect_data:/root/.prefect
    networks:
      - ingestion-net

  orion:
    build:
      context: ./simulation_data_prep # Adjusted build context
      dockerfile: orion.Dockerfile # Relative path from context
    command: prefect server start --host 0.0.0.0 --log-level debug
    # Map host port 4201 to container port 4200 for UI access
    ports:
      - "4201:4200"
    environment:
      - PREFECT_LOGGING_LEVEL=DEBUG
      # Point the UI (browser) to the host port where the API is exposed
      - PREFECT_UI_API_URL=http://localhost:4201/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@db:5432/prefect
    volumes:
      - prefect_db:/root/.prefect/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:4200/health/live || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ingestion-net

  mlflow-server:
    build:
      context: ./simulation_data_prep # Adjusted build context
      dockerfile: mlflow.Dockerfile # Relative path from context
    command: >
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql+psycopg2://postgres:postgres@db:5432/mlflow --default-artifact-root /mlflow/artifacts
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - mlflow_data:/mlflow/artifacts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ingestion-net

  # Test service for Python pipeline unit tests
  test:
    build:
      context: ./simulation_data_prep # Adjusted build context
      dockerfile: Dockerfile
    working_dir: /app # Set working directory for consistency
    env_file:
      - ./.env # Load from the same directory as this docker-compose.yml
    depends_on:
      db:
        condition: service_healthy
    entrypoint: [ "pytest", "src/tests", "--maxfail=1" ]
    volumes:
      # Mount source code needed for tests
      - ./simulation_data_prep/src:/app/src:ro
      - ./simulation_data_prep/dao:/app/dao:ro
      - ./simulation_data_prep/transforms:/app/transforms:ro
      - ./simulation_data_prep/loading:/app/loading:ro # If needed by imports
      - ./simulation_data_prep/validation:/app/validation:ro # If needed by imports
      # Mount config file needed by tests
      - ./simulation_data_prep/plant_config.json:/app/plant_config.json:ro
      # Mount sample data needed by tests (relative to docker-compose.yml location)
      - ../Data:/app/data:ro
    networks:
      - ingestion-net

  # --- New one-shot service for Prefect Deployment ---
  prefect-deployer:
    build:
      context: ./simulation_data_prep
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - ingestion-net
    env_file:
      - ./.env
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    command: ["echo", "Deployer container ready, awaiting command..."]
    volumes:
      - ./simulation_data_prep/src:/app/src
      - ./simulation_data_prep/dao:/app/dao
      - ./simulation_data_prep/transforms:/app/transforms
      - ./simulation_data_prep/loading:/app/loading
      - ./simulation_data_prep/validation:/app/validation
      - ./simulation_data_prep/prefect.yaml:/app/prefect.yaml # Mount the Prefect config file
    working_dir: /app # Ensure this matches the target path, or adjust target path if WORKDIR is different

# --- Volumes ---
volumes:
  postgres-data:
  redis-data:
  pgadmin-data:
  prefect_data:
  prefect_db:
  mlflow_data:

# --- Network ---
networks:
  ingestion-net:
    name: ingestion-net
    driver: bridge
