[package]
name = "data_pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
glob = "0.3" 